# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React - Build and Test

on:
  pull_request:
    branches: [ "master" ]
    paths: 
      - "react/**"

env:
  node-version: 16.x
  
defaults:
  run:
    working-directory: react

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - run: npm ci
    
    - run: npm run build
    
    - run: npm test
